In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
            'splitter':['best', 'random'],'max_features':['int', 'float','sqrt', 'log2']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
80 fits failed out of a total of 160.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
27 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'int' instead.

--------------------------------------------------------------------------------
13 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'int' instead.

--------------------------------------------------------------------------------
11 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'float' instead.

--------------------------------------------------------------------------------
29 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'float' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan 0.63918904 0.57979469
 0.64381658 0.60337099        nan        nan        nan        nan
 0.6313793  0.55565046 0.6273187  0.51989502        nan        nan
        nan        nan 0.49217344 0.52551777 0.60895811 0.57199014
        nan        nan        nan        nan 0.64507359 0.59260507
 0.6255967  0.60067327]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['int', 'float', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [10]:
result=grid.cv_results_

In [11]:
result

{'mean_fit_time': array([0.00359073, 0.00311584, 0.00211902, 0.00122056, 0.01113915,
        0.00882726, 0.00650907, 0.00526972, 0.00138679, 0.00098543,
        0.00095534, 0.001087  , 0.00502253, 0.00615282, 0.00665736,
        0.00580831, 0.00116773, 0.00189557, 0.00105848, 0.00106945,
        0.02064314, 0.01819768, 0.01879454, 0.014077  , 0.00094714,
        0.00100784, 0.00096459, 0.00093894, 0.0070796 , 0.00568929,
        0.00831714, 0.00524468]),
 'std_fit_time': array([4.69422136e-04, 1.26159437e-03, 1.32016765e-03, 1.80432156e-04,
        3.98725815e-03, 3.35305494e-03, 9.37494195e-04, 8.45880134e-04,
        5.09245400e-04, 1.87462414e-04, 2.71683929e-04, 8.42945602e-05,
        7.21364463e-04, 7.34005482e-04, 6.08114860e-04, 1.72409910e-03,
        3.52818899e-05, 1.07318120e-03, 2.86822470e-04, 2.22731377e-04,
        2.94109159e-03, 9.32852128e-04, 3.24983179e-03, 1.17278458e-03,
        1.42073597e-04, 9.39057390e-05, 1.53139384e-04, 9.56211767e-05,
        1.00939958e-03, 1.24619731e-03, 1.83143278e-03, 1.64305459e-03]),
 'mean_score_time': array([0.        , 0.        , 0.        , 0.        , 0.0069438 ,
        0.00303802, 0.00358953, 0.0032558 , 0.        , 0.        ,
        0.        , 0.        , 0.00330863, 0.00313931, 0.00354977,
        0.00353522, 0.        , 0.        , 0.        , 0.        ,
        0.00396657, 0.00399656, 0.00337796, 0.0030756 , 0.        ,
        0.        , 0.        , 0.        , 0.0030077 , 0.00294619,
        0.00402164, 0.00355558]),
 'std_score_time': array([0.        , 0.        , 0.        , 0.        , 0.00237018,
        0.00034856, 0.0005808 , 0.0005083 , 0.        , 0.        ,
        0.        , 0.        , 0.00030988, 0.00031883, 0.00034142,
        0.00099227, 0.        , 0.        , 0.        , 0.        ,
        0.00066885, 0.00105821, 0.00062387, 0.000667  , 0.        ,
        0.        , 0.        , 0.        , 0.00040762, 0.00050407,
        0.00161282, 0.00027404]),
 'param_criterion': masked_array(data=['squared_error', 'squared_error', 'squared_error',
                    'squared_error', 'squared_error', 'squared_error',
                    'squared_error', 'squared_error', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'absolute_error', 'absolute_error',
                    'absolute_error', 'absolute_error', 'absolute_error',
                    'absolute_error', 'absolute_error', 'absolute_error',
                    'poisson', 'poisson', 'poisson', 'poisson', 'poisson',
                    'poisson', 'poisson', 'poisson'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_max_features': masked_array(data=['int', 'int', 'float', 'float', 'sqrt', 'sqrt', 'log2',
                    'log2', 'int', 'int', 'float', 'float', 'sqrt', 'sqrt',
                    'log2', 'log2', 'int', 'int', 'float', 'float', 'sqrt',
                    'sqrt', 'log2', 'log2', 'int', 'int', 'float', 'float',
                    'sqrt', 'sqrt', 'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'criterion': 'squared_error',
   'max_features': 'int',
   'splitter': 'best'},
  {'criterion': 'squared_error', 'max_features': 'int', 'splitter': 'random'},
  {'criterion': 'squared_error', 'max_features': 'float', 'splitter': 'best'},
  {'criterion': 'squared_error',
   'max_features': 'float',
   'splitter': 'random'},
  {'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'int', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'int', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'float', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'float', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'int', 'splitter': 'best'},
  {'criterion': 'absolute_error', 'max_features': 'int', 'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'float', 'splitter': 'best'},
  {'criterion': 'absolute_error',
   'max_features': 'float',
   'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'absolute_error',
   'max_features': 'sqrt',
   'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'absolute_error',
   'max_features': 'log2',
   'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'int', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'int', 'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'float', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'float', 'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'log2', 'splitter': 'random'}],
 'split0_test_score': array([       nan,        nan,        nan,        nan, 0.66587876,
        0.64331662, 0.64797919, 0.74570976,        nan,        nan,
               nan,        nan, 0.76935779, 0.68674707, 0.55803691,
        0.67194326,        nan,        nan,        nan,        nan,
        0.72185551, 0.40175924, 0.66420062, 0.49330987,        nan,
               nan,        nan,        nan, 0.62987123, 0.68144391,
        0.66489857, 0.6890517 ]),
 'split1_test_score': array([       nan,        nan,        nan,        nan, 0.64241517,
        0.53530622, 0.67514975, 0.63180657,        nan,        nan,
               nan,        nan, 0.60925896, 0.61014874, 0.64475091,
        0.43109445,        nan,        nan,        nan,        nan,
        0.44480707, 0.44283194, 0.52891908, 0.40448681,        nan,
               nan,        nan,        nan, 0.61579673, 0.51677352,
        0.48695926, 0.64409175]),
 'split2_test_score': array([       nan,        nan,        nan,        nan, 0.68709193,
        0.49378907, 0.68519612, 0.59178789,        nan,        nan,
               nan,        nan, 0.67220856, 0.55873978, 0.72353234,
        0.66679496,        nan,        nan,        nan,        nan,
        0.41556091, 0.62746238, 0.47404258, 0.62217191,        nan,
               nan,        nan,        nan, 0.71676046, 0.58129436,
        0.68614603, 0.57427855]),
 'split3_test_score': array([       nan,        nan,        nan,        nan, 0.59075042,
        0.6223424 , 0.62509804, 0.5272472 ,        nan,        nan,
               nan,        nan, 0.62719203, 0.44096647, 0.62063841,
        0.47082619,        nan,        nan,        nan,        nan,
        0.28582463, 0.56604408, 0.65762802, 0.69791485,        nan,
               nan,        nan,        nan, 0.61280384, 0.7070966 ,
        0.59345648, 0.51723965]),
 'split4_test_score': array([       nan,        nan,        nan,        nan, 0.60980894,
        0.60421915, 0.58565981, 0.52030355,        nan,        nan,
               nan,        nan, 0.47887915, 0.48165025, 0.58963493,
        0.35881625,        nan,        nan,        nan,        nan,
        0.59281911, 0.58949119, 0.72000025, 0.64206728,        nan,
               nan,        nan,        nan, 0.6501357 , 0.47641696,
        0.69652314, 0.57870472]),
 'mean_test_score': array([       nan,        nan,        nan,        nan, 0.63918904,
        0.57979469, 0.64381658, 0.60337099,        nan,        nan,
               nan,        nan, 0.6313793 , 0.55565046, 0.6273187 ,
        0.51989502,        nan,        nan,        nan,        nan,
        0.49217344, 0.52551777, 0.60895811, 0.57199014,        nan,
               nan,        nan,        nan, 0.64507359, 0.59260507,
        0.6255967 , 0.60067327]),
 'std_test_score': array([       nan,        nan,        nan,        nan, 0.03529001,
        0.05624604, 0.03589973, 0.08233846,        nan,        nan,
               nan,        nan, 0.09430613, 0.08808448, 0.05625941,
        0.12723044,        nan,        nan,        nan,        nan,
        0.15071582, 0.08749949, 0.09204271, 0.10726975,        nan,
               nan,        nan,        nan, 0.0381948 , 0.0898651 ,
        0.07809578, 0.05972668]),
 'rank_test_score': array([17, 17, 17, 17,  3, 11,  2,  8, 17, 17, 17, 17,  4, 13,  5, 15, 17,
        17, 17, 17, 16, 14,  7, 12, 17, 17, 17, 17,  1, 10,  6,  9],
       dtype=int32)}

In [12]:

table=pd.DataFrame.from_dict(result)

In [ ]:
table

In [13]:
table.columns
table=table.sort_values(by='rank_test_score')
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
28,0.007080,0.001009,0.003008,0.000408,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.629871,0.615797,0.716760,0.612804,0.650136,0.645074,0.038195,1
6,0.006509,0.000937,0.003590,0.000581,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.647979,0.675150,0.685196,0.625098,0.585660,0.643817,0.035900,2
4,0.011139,0.003987,0.006944,0.002370,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.665879,0.642415,0.687092,0.590750,0.609809,0.639189,0.035290,3
12,0.005023,0.000721,0.003309,0.000310,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.769358,0.609259,0.672209,0.627192,0.478879,0.631379,0.094306,4
14,0.006657,0.000608,0.003550,0.000341,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.558037,0.644751,0.723532,0.620638,0.589635,0.627319,0.056259,5
30,0.008317,0.001831,0.004022,0.001613,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.664899,0.486959,0.686146,0.593456,0.696523,0.625597,0.078096,6
22,0.018795,0.003250,0.003378,0.000624,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.664201,0.528919,0.474043,0.657628,0.720000,0.608958,0.092043,7
7,0.005270,0.000846,0.003256,0.000508,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.745710,0.631807,0.591788,0.527247,0.520304,0.603371,0.082338,8
31,0.005245,0.001643,0.003556,0.000274,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.689052,0.644092,0.574279,0.517240,0.578705,0.600673,0.059727,9
29,0.005689,0.001246,0.002946,0.000504,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.681444,0.516774,0.581294,0.707097,0.476417,0.592605,0.089865,10
5,0.008827,0.003353,0.003038,0.000349,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.643317,0.535306,0.493789,0.622342,0.604219,0.579795,0.056246,11
23,0.014077,0.001173,0.003076,0.000667,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.493310,0.404487,0.622172,0.697915,0.642067,0.571990,0.107270,12
13,0.006153,0.000734,0.003139,0.000319,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.686747,0.610149,0.558740,0.440966,0.481650,0.555650,0.088084,13
21,0.018198,0.000933,0.003997,0.001058,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.401759,0.442832,0.627462,0.566044,0.589491,0.525518,0.087499,14
15,0.005808,0.001724,0.003535,0.000992,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.671943,0.431094,0.666795,0.470826,0.358816,0.519895,0.127230,15
20,0.020643,0.002941,0.003967,0.000669,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.721856,0.444807,0.415561,0.285825,0.592819,0.492173,0.150716,16
10,0.000955,0.000272,0.000000,0.000000,friedman_mse,float,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.003116,0.001262,0.000000,0.000000,squared_error,int,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.002119,0.001320,0.000000,0.000000,squared_error,float,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
27,0.000939,0.000096,0.000000,0.000000,poisson,float,random,"{'criterion': 'poisson', 'max_features': 'floa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
26,0.000965,0.000153,0.000000,0.000000,poisson,float,best,"{'criterion': 'poisson', 'max_features': 'floa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
25,0.001008,0.000094,0.000000,0.000000,poisson,int,random,"{'criterion': 'poisson', 'max_features': 'int'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
24,0.000947,0.000142,0.000000,0.000000,poisson,int,best,"{'criterion': 'poisson', 'max_features': 'int'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
3,0.001221,0.000180,0.000000,0.000000,squared_error,float,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.001387,0.000509,0.000000,0.000000,friedman_mse,int,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
9,0.000985,0.000187,0.000000,0.000000,friedman_mse,int,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.001069,0.000223,0.000000,0.000000,absolute_error,float,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
18,0.001058,0.000287,0.000000,0.000000,absolute_error,float,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
17,0.001896,0.001073,0.000000,0.000000,absolute_error,int,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
16,0.001168,0.000035,0.000000,0.000000,absolute_error,int,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
11,0.001087,0.000084,0.000000,0.000000,friedman_mse,float,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
0,0.003591,0.000469,0.000000,0.000000,squared_error,int,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17

In [14]:
dttable=table[['param_criterion','param_splitter','std_test_score','rank_test_score']]
dttable.columns=[['Criterion','Splitter','STD Score','Rank']]
dttable

         Criterion Splitter STD Score Rank
28         poisson     best  0.038195    1
6    squared_error     best  0.035900    2
4    squared_error     best  0.035290    3
12    friedman_mse     best  0.094306    4
14    friedman_mse     best  0.056259    5
30         poisson     best  0.078096    6
22  absolute_error     best  0.092043    7
7    squared_error   random  0.082338    8
31         poisson   random  0.059727    9
29         poisson   random  0.089865   10
5    squared_error   random  0.056246   11
23  absolute_error   random  0.107270   12
13    friedman_mse   random  0.088084   13
21  absolute_error   random  0.087499   14
15    friedman_mse   random  0.127230   15
20  absolute_error     best  0.150716   16
10    friedman_mse     best       NaN   17
1    squared_error   random       NaN   17
2    squared_error     best       NaN   17
27         poisson   random       NaN   17
26         poisson     best       NaN   17
25         poisson   random       NaN   17
24         poisson     best       NaN   17
3    squared_error   random       NaN   17
8     friedman_mse     best       NaN   17
9     friedman_mse   random       NaN   17
19  absolute_error   random       NaN   17
18  absolute_error     best       NaN   17
17  absolute_error   random       NaN   17
16  absolute_error     best       NaN   17
11    friedman_mse   random       NaN   17
0    squared_error     best       NaN   17

In [15]:
y_pred=grid.predict(x_test)
from sklearn.metrics import r2_score
r2score=r2_score(y_test,y_pred)
r2score

0.695568130331707

In [ ]:
Age = float(input("Please enter your age: "))
BMI = float(input("Please enter your BMI: "))
Children = float(input("Please enter number of children: "))

Gender = input("Please enter your gender: ").lower()
if Gender == "male":
    gender = 1
else:
    gender = 0

Smoker = input("Do you smoke? (yes/no): ").lower()
if Smoker == "yes":
    smoker = 1
else:
    smoker = 0

charger_prediction = grid.predict([[Age, BMI, Children, gender, smoker]])

print("Estimated Charge is:", charger_prediction[0])