In [6]:
import pandas as pd

In [7]:
dataset=pd.read_csv("insurance_pre.csv")

In [8]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [9]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [10]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [11]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [12]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid={'criterion':['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
            'splitter':['best', 'random'],'max_features':['int', 'float','sqrt', 'log2']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 32 candidates, totalling 160 fits

C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
80 fits failed out of a total of 160.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'int' instead.

--------------------------------------------------------------------------------
24 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'int' instead.

--------------------------------------------------------------------------------
24 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'float' instead.

--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'float' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan 0.64524607 0.52606146
 0.59749527 0.55477607        nan        nan        nan        nan
 0.57153457 0.61224843 0.62410351 0.53453203        nan        nan
        nan        nan 0.62759938 0.63528947 0.60692656 0.61390934
        nan        nan        nan        nan 0.55486696 0.5683337
 0.49315851 0.59510742]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['int', 'float', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [15]:
result=grid.cv_results_

In [16]:
result

{'mean_fit_time': array([0.00467806, 0.00422821, 0.00525799, 0.00577507, 0.0264482 ,
        0.01648502, 0.02374544, 0.02081919, 0.00283766, 0.00248971,
        0.00204654, 0.00187201, 0.01606956, 0.0120255 , 0.0149744 ,
        0.01096325, 0.00192499, 0.00227947, 0.00205655, 0.00248151,
        0.0567327 , 0.03457646, 0.04968467, 0.04323764, 0.0030849 ,
        0.0018692 , 0.00331535, 0.00333371, 0.01928225, 0.01055837,
        0.02071838, 0.01167231]),
 'std_fit_time': array([0.00173031, 0.00165841, 0.00144514, 0.00208458, 0.00885011,
        0.00341443, 0.00552865, 0.00149065, 0.00123418, 0.00183252,
        0.00093594, 0.00069521, 0.00888622, 0.00149903, 0.00291015,
        0.00271391, 0.00083413, 0.00129335, 0.00141558, 0.00165129,
        0.00681014, 0.00592334, 0.0046273 , 0.00565337, 0.00357577,
        0.00123149, 0.00110327, 0.00193633, 0.00344461, 0.00209552,
        0.0053738 , 0.00427443]),
 'mean_score_time': array([0.        , 0.        , 0.        , 0.        , 0.01331921,
        0.01003194, 0.01188374, 0.01311522, 0.        , 0.        ,
        0.        , 0.        , 0.00538731, 0.0082581 , 0.00912356,
        0.00701785, 0.        , 0.        , 0.        , 0.        ,
        0.00864973, 0.00815725, 0.00779862, 0.0078939 , 0.        ,
        0.        , 0.        , 0.        , 0.0056313 , 0.00963092,
        0.00803804, 0.00791769]),
 'std_score_time': array([0.        , 0.        , 0.        , 0.        , 0.00128881,
        0.00138054, 0.00389842, 0.00454712, 0.        , 0.        ,
        0.        , 0.        , 0.00185562, 0.00156736, 0.00224407,
        0.0025725 , 0.        , 0.        , 0.        , 0.        ,
        0.00381522, 0.00086341, 0.00069285, 0.0011524 , 0.        ,
        0.        , 0.        , 0.        , 0.001637  , 0.002596  ,
        0.00149953, 0.00402358]),
 'param_criterion': masked_array(data=['squared_error', 'squared_error', 'squared_error',
                    'squared_error', 'squared_error', 'squared_error',
                    'squared_error', 'squared_error', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'friedman_mse', 'friedman_mse',
                    'friedman_mse', 'absolute_error', 'absolute_error',
                    'absolute_error', 'absolute_error', 'absolute_error',
                    'absolute_error', 'absolute_error', 'absolute_error',
                    'poisson', 'poisson', 'poisson', 'poisson', 'poisson',
                    'poisson', 'poisson', 'poisson'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_max_features': masked_array(data=['int', 'int', 'float', 'float', 'sqrt', 'sqrt', 'log2',
                    'log2', 'int', 'int', 'float', 'float', 'sqrt', 'sqrt',
                    'log2', 'log2', 'int', 'int', 'float', 'float', 'sqrt',
                    'sqrt', 'log2', 'log2', 'int', 'int', 'float', 'float',
                    'sqrt', 'sqrt', 'log2', 'log2'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_splitter': masked_array(data=['best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random', 'best', 'random', 'best', 'random',
                    'best', 'random'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'criterion': 'squared_error',
   'max_features': 'int',
   'splitter': 'best'},
  {'criterion': 'squared_error', 'max_features': 'int', 'splitter': 'random'},
  {'criterion': 'squared_error', 'max_features': 'float', 'splitter': 'best'},
  {'criterion': 'squared_error',
   'max_features': 'float',
   'splitter': 'random'},
  {'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'squared_error', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'squared_error', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'int', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'int', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'float', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'float', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'int', 'splitter': 'best'},
  {'criterion': 'absolute_error', 'max_features': 'int', 'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'float', 'splitter': 'best'},
  {'criterion': 'absolute_error',
   'max_features': 'float',
   'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'absolute_error',
   'max_features': 'sqrt',
   'splitter': 'random'},
  {'criterion': 'absolute_error', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'absolute_error',
   'max_features': 'log2',
   'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'int', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'int', 'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'float', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'float', 'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'sqrt', 'splitter': 'random'},
  {'criterion': 'poisson', 'max_features': 'log2', 'splitter': 'best'},
  {'criterion': 'poisson', 'max_features': 'log2', 'splitter': 'random'}],
 'split0_test_score': array([       nan,        nan,        nan,        nan, 0.73923615,
        0.68602266, 0.77822566, 0.69059755,        nan,        nan,
               nan,        nan, 0.76100375, 0.74087766, 0.67145275,
        0.57310897,        nan,        nan,        nan,        nan,
        0.76062358, 0.70919387, 0.61390649, 0.80467897,        nan,
               nan,        nan,        nan, 0.78468179, 0.68128405,
        0.68999533, 0.67701556]),
 'split1_test_score': array([       nan,        nan,        nan,        nan, 0.61021573,
        0.54991676, 0.58910275, 0.47086414,        nan,        nan,
               nan,        nan, 0.41830047, 0.56585519, 0.58475382,
        0.57270591,        nan,        nan,        nan,        nan,
        0.60122286, 0.65667516, 0.59022576, 0.5902798 ,        nan,
               nan,        nan,        nan, 0.36710545, 0.49983145,
        0.61500328, 0.52411772]),
 'split2_test_score': array([       nan,        nan,        nan,        nan, 0.60059004,
        0.51921179, 0.30968749, 0.56028513,        nan,        nan,
               nan,        nan, 0.33257616, 0.62052697, 0.6530139 ,
        0.49699331,        nan,        nan,        nan,        nan,
        0.55202636, 0.66960311, 0.59676473, 0.44091824,        nan,
               nan,        nan,        nan, 0.37753409, 0.59835999,
        0.46734569, 0.6075651 ]),
 'split3_test_score': array([       nan,        nan,        nan,        nan, 0.64950878,
        0.28886406, 0.65752119, 0.51942378,        nan,        nan,
               nan,        nan, 0.70059639, 0.57097927, 0.72191644,
        0.54725679,        nan,        nan,        nan,        nan,
        0.59031758, 0.56100976, 0.65570442, 0.62041011,        nan,
               nan,        nan,        nan, 0.63251529, 0.4972259 ,
        0.06369073, 0.53924075]),
 'split4_test_score': array([       nan,        nan,        nan,        nan, 0.62667963,
        0.58629203, 0.65293928, 0.53270974,        nan,        nan,
               nan,        nan, 0.64519606, 0.56300308, 0.48938065,
        0.48259517,        nan,        nan,        nan,        nan,
        0.63380653, 0.57996545, 0.57803138, 0.61325958,        nan,
               nan,        nan,        nan, 0.6124982 , 0.5649671 ,
        0.62975752, 0.62759798]),
 'mean_test_score': array([       nan,        nan,        nan,        nan, 0.64524607,
        0.52606146, 0.59749527, 0.55477607,        nan,        nan,
               nan,        nan, 0.57153457, 0.61224843, 0.62410351,
        0.53453203,        nan,        nan,        nan,        nan,
        0.62759938, 0.63528947, 0.60692656, 0.61390934,        nan,
               nan,        nan,        nan, 0.55486696, 0.5683337 ,
        0.49315851, 0.59510742]),
 'std_test_score': array([       nan,        nan,        nan,        nan, 0.04983634,
        0.13122035, 0.15636136, 0.07383189,        nan,        nan,
               nan,        nan, 0.16647123, 0.06766771, 0.08042857,
        0.03798404,        nan,        nan,        nan,        nan,
        0.07145754, 0.05599082, 0.02700041, 0.11568925,        nan,
               nan,        nan,        nan, 0.16054084, 0.06843913,
        0.22687399, 0.05671049]),
 'rank_test_score': array([17, 17, 17, 17,  1, 15,  8, 13, 17, 17, 17, 17, 10,  6,  4, 14, 17,
        17, 17, 17,  3,  2,  7,  5, 17, 17, 17, 17, 12, 11, 16,  9],
       dtype=int32)}

In [17]:

table=pd.DataFrame.from_dict(result)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004678,0.001730,0.000000,0.000000,squared_error,int,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.004228,0.001658,0.000000,0.000000,squared_error,int,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.005258,0.001445,0.000000,0.000000,squared_error,float,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
3,0.005775,0.002085,0.000000,0.000000,squared_error,float,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
4,0.026448,0.008850,0.013319,0.001289,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.739236,0.610216,0.600590,0.649509,0.626680,0.645246,0.049836,1
5,0.016485,0.003414,0.010032,0.001381,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.686023,0.549917,0.519212,0.288864,0.586292,0.526061,0.131220,15
6,0.023745,0.005529,0.011884,0.003898,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.778226,0.589103,0.309687,0.657521,0.652939,0.597495,0.156361,8
7,0.020819,0.001491,0.013115,0.004547,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.690598,0.470864,0.560285,0.519424,0.532710,0.554776,0.073832,13
8,0.002838,0.001234,0.000000,0.000000,friedman_mse,int,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
9,0.002490,0.001833,0.000000,0.000000,friedman_mse,int,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
10,0.002047,0.000936,0.000000,0.000000,friedman_mse,float,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
11,0.001872,0.000695,0.000000,0.000000,friedman_mse,float,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
12,0.016070,0.008886,0.005387,0.001856,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.761004,0.418300,0.332576,0.700596,0.645196,0.571535,0.166471,10
13,0.012025,0.001499,0.008258,0.001567,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.740878,0.565855,0.620527,0.570979,0.563003,0.612248,0.067668,6
14,0.014974,0.002910,0.009124,0.002244,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.671453,0.584754,0.653014,0.721916,0.489381,0.624104,0.080429,4
15,0.010963,0.002714,0.007018,0.002572,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.573109,0.572706,0.496993,0.547257,0.482595,0.534532,0.037984,14
16,0.001925,0.000834,0.000000,0.000000,absolute_error,int,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
17,0.002279,0.001293,0.000000,0.000000,absolute_error,int,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
18,0.002057,0.001416,0.000000,0.000000,absolute_error,float,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.002482,0.001651,0.000000,0.000000,absolute_error,float,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.056733,0.006810,0.008650,0.003815,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.760624,0.601223,0.552026,0.590318,0.633807,0.627599,0.071458,3
21,0.034576,0.005923,0.008157,0.000863,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.709194,0.656675,0.669603,0.561010,0.579965,0.635289,0.055991,2
22,0.049685,0.004627,0.007799,0.000693,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.613906,0.590226,0.596765,0.655704,0.578031,0.606927,0.027000,7
23,0.043238,0.005653,0.007894,0.001152,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.804679,0.590280,0.440918,0.620410,0.613260,0.613909,0.115689,5
24,0.003085,0.003576,0.000000,0.000000,poisson,int,best,"{'criterion': 'poisson', 'max_features': 'int'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
25,0.001869,0.001231,0.000000,0.000000,poisson,int,random,"{'criterion': 'poisson', 'max_features': 'int'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
26,0.003315,0.001103,0.000000,0.000000,poisson,float,best,"{'criterion': 'poisson', 'max_features': 'floa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
27,0.003334,0.001936,0.000000,0.000000,poisson,float,random,"{'criterion': 'poisson', 'max_features': 'floa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
28,0.019282,0.003445,0.005631,0.001637,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.784682,0.367105,0.377534,0.632515,0.612498,0.554867,0.160541,12
29,0.010558,0.002096,0.009631,0.002596,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.681284,0.499831,0.598360,0.497226,0.564967,0.568334,0.068439,11
30,0.020718,0.005374,0.008038,0.001500,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.689995,0.615003,0.467346,0.063691,0.629758,0.493159,0.226874,16
31,0.011672,0.004274,0.007918,0.004024,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.677016,0.524118,0.607565,0.539241,0.627598,0.595107,0.056710,9

In [31]:
table.columns
table=table.sort_values(by='rank_test_score')
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
4,0.026448,0.008850,0.013319,0.001289,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.739236,0.610216,0.600590,0.649509,0.626680,0.645246,0.049836,1
21,0.034576,0.005923,0.008157,0.000863,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.709194,0.656675,0.669603,0.561010,0.579965,0.635289,0.055991,2
20,0.056733,0.006810,0.008650,0.003815,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.760624,0.601223,0.552026,0.590318,0.633807,0.627599,0.071458,3
14,0.014974,0.002910,0.009124,0.002244,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.671453,0.584754,0.653014,0.721916,0.489381,0.624104,0.080429,4
23,0.043238,0.005653,0.007894,0.001152,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.804679,0.590280,0.440918,0.620410,0.613260,0.613909,0.115689,5
13,0.012025,0.001499,0.008258,0.001567,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.740878,0.565855,0.620527,0.570979,0.563003,0.612248,0.067668,6
22,0.049685,0.004627,0.007799,0.000693,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.613906,0.590226,0.596765,0.655704,0.578031,0.606927,0.027000,7
6,0.023745,0.005529,0.011884,0.003898,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.778226,0.589103,0.309687,0.657521,0.652939,0.597495,0.156361,8
31,0.011672,0.004274,0.007918,0.004024,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.677016,0.524118,0.607565,0.539241,0.627598,0.595107,0.056710,9
12,0.016070,0.008886,0.005387,0.001856,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.761004,0.418300,0.332576,0.700596,0.645196,0.571535,0.166471,10
29,0.010558,0.002096,0.009631,0.002596,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.681284,0.499831,0.598360,0.497226,0.564967,0.568334,0.068439,11
28,0.019282,0.003445,0.005631,0.001637,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.784682,0.367105,0.377534,0.632515,0.612498,0.554867,0.160541,12
7,0.020819,0.001491,0.013115,0.004547,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.690598,0.470864,0.560285,0.519424,0.532710,0.554776,0.073832,13
15,0.010963,0.002714,0.007018,0.002572,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.573109,0.572706,0.496993,0.547257,0.482595,0.534532,0.037984,14
5,0.016485,0.003414,0.010032,0.001381,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.686023,0.549917,0.519212,0.288864,0.586292,0.526061,0.131220,15
30,0.020718,0.005374,0.008038,0.001500,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.689995,0.615003,0.467346,0.063691,0.629758,0.493159,0.226874,16
1,0.004228,0.001658,0.000000,0.000000,squared_error,int,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.005258,0.001445,0.000000,0.000000,squared_error,float,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
27,0.003334,0.001936,0.000000,0.000000,poisson,float,random,"{'criterion': 'poisson', 'max_features': 'floa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
26,0.003315,0.001103,0.000000,0.000000,poisson,float,best,"{'criterion': 'poisson', 'max_features': 'floa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
25,0.001869,0.001231,0.000000,0.000000,poisson,int,random,"{'criterion': 'poisson', 'max_features': 'int'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
24,0.003085,0.003576,0.000000,0.000000,poisson,int,best,"{'criterion': 'poisson', 'max_features': 'int'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
3,0.005775,0.002085,0.000000,0.000000,squared_error,float,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
10,0.002047,0.000936,0.000000,0.000000,friedman_mse,float,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.002838,0.001234,0.000000,0.000000,friedman_mse,int,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
9,0.002490,0.001833,0.000000,0.000000,friedman_mse,int,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.002482,0.001651,0.000000,0.000000,absolute_error,float,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
18,0.002057,0.001416,0.000000,0.000000,absolute_error,float,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
17,0.002279,0.001293,0.000000,0.000000,absolute_error,int,random,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
16,0.001925,0.000834,0.000000,0.000000,absolute_error,int,best,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
11,0.001872,0.000695,0.000000,0.000000,friedman_mse,float,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
0,0.004678,0.001730,0.000000,0.000000,squared_error,int,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17

In [32]:
dttable=table[['param_criterion','param_splitter','std_test_score','rank_test_score']]
dttable.columns=[['Criterion','Splitter','STD Score','Rank']]
dttable

         Criterion Splitter STD Score Rank
4    squared_error     best  0.049836    1
21  absolute_error   random  0.055991    2
20  absolute_error     best  0.071458    3
14    friedman_mse     best  0.080429    4
23  absolute_error   random  0.115689    5
13    friedman_mse   random  0.067668    6
22  absolute_error     best  0.027000    7
6    squared_error     best  0.156361    8
31         poisson   random  0.056710    9
12    friedman_mse     best  0.166471   10
29         poisson   random  0.068439   11
28         poisson     best  0.160541   12
7    squared_error   random  0.073832   13
15    friedman_mse   random  0.037984   14
5    squared_error   random  0.131220   15
30         poisson     best  0.226874   16
1    squared_error   random       NaN   17
2    squared_error     best       NaN   17
27         poisson   random       NaN   17
26         poisson     best       NaN   17
25         poisson   random       NaN   17
24         poisson     best       NaN   17
3    squared_error   random       NaN   17
10    friedman_mse     best       NaN   17
8     friedman_mse     best       NaN   17
9     friedman_mse   random       NaN   17
19  absolute_error   random       NaN   17
18  absolute_error     best       NaN   17
17  absolute_error   random       NaN   17
16  absolute_error     best       NaN   17
11    friedman_mse   random       NaN   17
0    squared_error     best       NaN   17

In [33]:
Age = float(input("Please enter your age: "))
BMI = float(input("Please enter your BMI: "))
Children = float(input("Please enter number of children: "))

Gender = input("Please enter your gender: ").lower()
if Gender == "male":
    gender = 1
else:
    gender = 0

Smoker = input("Do you smoke? (yes/no): ").lower()
if Smoker == "yes":
    smoker = 1
else:
    smoker = 0

charger_prediction = grid.predict([[Age, BMI, Children, gender, smoker]])

print("Estimated Charge is:", charger_prediction[0])

Please enter your age:  23
Please enter your BMI:  34
Please enter number of children:  2
Please enter your gender:  male
Do you smoke? (yes/no):  yes

Estimated Charge is: 36124.5737

C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(