In [1]:
import pandas as pd
import numpy as np

In [3]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [8]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.3,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={'kernel':['linear', 'poly', 'rbf', 'sigmoid'],'C':[10,100,1000,2000,3000],'gamma':['scale','auto']}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\gayut\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             verbose=3)

In [15]:
result=grid.cv_results_

In [16]:
result

{'mean_fit_time': array([0.09813561, 0.07921224, 0.06328673, 0.0632266 , 0.04363747,
        0.04317183, 0.05607328, 0.05691118, 0.05361228, 0.04686217,
        0.0582047 , 0.06464801, 0.06179218, 0.05546145, 0.06719604,
        0.0660007 , 0.07352934, 0.09259963, 0.10407443, 0.0840847 ,
        0.07148023, 0.06638017, 0.06851106, 0.06502171, 0.07333164,
        0.10005841, 0.07290545, 0.06773672, 0.07660141, 0.11531129,
        0.0784162 , 0.06602383, 0.08388658, 0.20133319, 0.07832694,
        0.06791081, 0.08415051, 0.16925416, 0.08375282, 0.06142931]),
 'std_fit_time': array([0.00290035, 0.02190198, 0.00512887, 0.00449834, 0.00084111,
        0.0010139 , 0.00155959, 0.00089049, 0.0007465 , 0.00068004,
        0.00099772, 0.00518309, 0.00458259, 0.00500649, 0.00351133,
        0.00603204, 0.00442078, 0.01753761, 0.02678055, 0.02180338,
        0.01240873, 0.00953247, 0.00071507, 0.00383249, 0.00493247,
        0.0089179 , 0.00317375, 0.00272205, 0.00659769, 0.02152387,
        0.00226951, 0.00147638, 0.00264354, 0.08500725, 0.00242247,
        0.0014621 , 0.00321992, 0.07313457, 0.00509567, 0.0056964 ]),
 'mean_score_time': array([0.0097837 , 0.01109037, 0.02691717, 0.01194425, 0.00875883,
        0.00958567, 0.02549448, 0.0129137 , 0.0086031 , 0.00834613,
        0.02535963, 0.01405802, 0.00984054, 0.01243987, 0.03062739,
        0.01255884, 0.01020646, 0.01189585, 0.02833414, 0.01293197,
        0.00827084, 0.00906863, 0.02442584, 0.01242495, 0.00783648,
        0.00905018, 0.02557945, 0.01204019, 0.00912929, 0.00906105,
        0.02490096, 0.01161876, 0.00834846, 0.00855579, 0.02430501,
        0.01114664, 0.00823083, 0.00810375, 0.02445536, 0.0121767 ]),
 'std_score_time': array([0.00075947, 0.00139995, 0.0017125 , 0.00049407, 0.00049757,
        0.00080897, 0.00083219, 0.00052349, 0.00046535, 0.00037083,
        0.00132256, 0.00327669, 0.00207062, 0.00243826, 0.01181994,
        0.00072283, 0.00195515, 0.00227995, 0.00537164, 0.00118156,
        0.00040266, 0.00129534, 0.00059317, 0.00042319, 0.00033272,
        0.0005895 , 0.00058417, 0.00032397, 0.00114791, 0.00041815,
        0.00105461, 0.00052819, 0.00079721, 0.00081349, 0.00110517,
        0.00044344, 0.00040818, 0.00094086, 0.00143473, 0.00384837]),
 'param_C': masked_array(data=[10, 10, 10, 10, 10, 10, 10, 10, 100, 100, 100, 100,
                    100, 100, 100, 100, 1000, 1000, 1000, 1000, 1000, 1000,
                    1000, 1000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
                    2000, 3000, 3000, 3000, 3000, 3000, 3000, 3000, 3000],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_gamma': masked_array(data=['scale', 'scale', 'scale', 'scale', 'auto', 'auto',
                    'auto', 'auto', 'scale', 'scale', 'scale', 'scale',
                    'auto', 'auto', 'auto', 'auto', 'scale', 'scale',
                    'scale', 'scale', 'auto', 'auto', 'auto', 'auto',
                    'scale', 'scale', 'scale', 'scale', 'auto', 'auto',
                    'auto', 'auto', 'scale', 'scale', 'scale', 'scale',
                    'auto', 'auto', 'auto', 'auto'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid', 'linear', 'poly',
                    'rbf', 'sigmoid', 'linear', 'poly', 'rbf', 'sigmoid',
                    'linear', 'poly', 'rbf', 'sigmoid'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 10, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'poly'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'},
  {'C': 100, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 100, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 100, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'},
  {'C': 100, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 100, 'gamma': 'auto', 'kernel': 'poly'},
  {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'},
  {'C': 1000, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 1000, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 1000, 'gamma': 'scale', 'kernel': 'sigmoid'},
  {'C': 1000, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 1000, 'gamma': 'auto', 'kernel': 'poly'},
  {'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'},
  {'C': 2000, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 2000, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 2000, 'gamma': 'scale', 'kernel': 'sigmoid'},
  {'C': 2000, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 2000, 'gamma': 'auto', 'kernel': 'poly'},
  {'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'},
  {'C': 3000, 'gamma': 'scale', 'kernel': 'linear'},
  {'C': 3000, 'gamma': 'scale', 'kernel': 'poly'},
  {'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'},
  {'C': 3000, 'gamma': 'scale', 'kernel': 'sigmoid'},
  {'C': 3000, 'gamma': 'auto', 'kernel': 'linear'},
  {'C': 3000, 'gamma': 'auto', 'kernel': 'poly'},
  {'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'},
  {'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}],
 'split0_test_score': array([ 0.37796942,  0.05496425,  0.00412586,  0.04964409,  0.37796942,
         0.05627368,  0.00405464,  0.04990486,  0.58447385,  0.53711683,
         0.30104054,  0.47892989,  0.58447385,  0.54064267,  0.30057297,
         0.47836438,  0.60530422,  0.82821255,  0.73333405,  0.40004431,
         0.60530422,  0.82963099,  0.7330437 ,  0.29608228,  0.60527653,
         0.84558061,  0.81429471, -0.38565762,  0.60527653,  0.84540306,
         0.81407566, -0.4018548 ,  0.65747018,  0.84687424,  0.82879465,
        -1.76187101,  0.65747018,  0.84677493,  0.82867012, -1.09089557]),
 'split1_test_score': array([ 0.47960111,  0.07129715,  0.01324394,  0.07632325,  0.47960111,
         0.06953185,  0.01336631,  0.07590543,  0.65581783,  0.57937309,
         0.33874084,  0.56320039,  0.65581783,  0.5750512 ,  0.33947441,
         0.56167332,  0.58872491,  0.80262236,  0.74589177,  0.36609665,
         0.58872491,  0.80262228,  0.74623177,  0.37228139,  0.58364579,
         0.80562419,  0.78097115, -0.53709822,  0.58364579,  0.80563899,
         0.78109214, -0.50808234,  0.58350133,  0.80533085,  0.79010467,
        -2.13930727,  0.58350133,  0.80532327,  0.79026508, -1.76104324]),
 'split2_test_score': array([ 0.31787188, -0.04651284, -0.1037751 , -0.04679758,  0.31787188,
        -0.04560054, -0.10382139, -0.04658456,  0.55337959,  0.47184037,
         0.17408608,  0.42715156,  0.55337959,  0.47483911,  0.1737081 ,
         0.42833118,  0.62322978,  0.7993483 ,  0.68703674,  0.24221738,
         0.62322978,  0.79961965,  0.68677347,  0.21640051,  0.6973683 ,
         0.81661184,  0.79422673, -0.47491217,  0.6973683 ,  0.81673326,
         0.79408088, -0.45282687,  0.69787509,  0.81728269,  0.81112288,
        -1.7043686 ,  0.69787509,  0.81730888,  0.81104864, -1.73434391]),
 'split3_test_score': array([ 0.33797922, -0.0241573 , -0.09516453, -0.04082408,  0.33797922,
        -0.02507884, -0.09511946, -0.04100353,  0.57693927,  0.53796609,
         0.21764123,  0.45124954,  0.57693927,  0.53573004,  0.217991  ,
         0.45045398,  0.53793069,  0.80058667,  0.71776936,  0.28846128,
         0.53793069,  0.80032064,  0.71792002,  0.29126459,  0.53254704,
         0.80513253,  0.79398276, -0.47733505,  0.53254704,  0.80514322,
         0.7940747 , -0.75101268,  0.52911665,  0.80523906,  0.81285679,
        -2.34083874,  0.52911665,  0.80519096,  0.81289193, -2.30437676]),
 'split4_test_score': array([ 0.32442228, -0.04965211, -0.10160151, -0.04652087,  0.32442228,
        -0.0495916 , -0.10160388, -0.04650724,  0.54688068,  0.42447762,
         0.18340338,  0.43219873,  0.54688068,  0.42464024,  0.18337524,
         0.4317012 ,  0.61672585,  0.73555531,  0.64917391,  0.35140737,
         0.61672585,  0.73557967,  0.64915813,  0.35132483,  0.68142533,
         0.75496159,  0.73366259, -0.11118672,  0.68142533,  0.75496149,
         0.73365588, -0.11185939,  0.65578454,  0.75898808,  0.74183529,
        -1.04873926,  0.65578454,  0.75899368,  0.74182895, -1.05027984]),
 'mean_test_score': array([ 3.67568780e-01,  1.18783088e-03, -5.66342673e-02, -1.63503920e-03,
         3.67568780e-01,  1.10690971e-03, -5.66247564e-02, -1.65700582e-03,
         5.83498244e-01,  5.10154800e-01,  2.42982415e-01,  4.70546023e-01,
         5.83498244e-01,  5.10180652e-01,  2.43024344e-01,  4.70104813e-01,
         5.94383090e-01,  7.93265039e-01,  7.06641165e-01,  3.29645399e-01,
         5.94383090e-01,  7.93554645e-01,  7.06625418e-01,  3.05470720e-01,
         6.20052595e-01,  8.05582155e-01,  7.83427585e-01, -3.97237956e-01,
         6.20052595e-01,  8.05576005e-01,  7.83395853e-01, -4.45127213e-01,
         6.24749558e-01,  8.06742981e-01,  7.96942859e-01, -1.79902498e+00,
         6.24749558e-01,  8.06718342e-01,  7.96940945e-01, -1.58818786e+00]),
 'std_test_score': array([0.05977685, 0.0515939 , 0.05348579, 0.05347376, 0.05977685,
        0.0513088 , 0.05350369, 0.05339051, 0.03878679, 0.05495483,
        0.0655423 , 0.04976157, 0.03878679, 0.05358186, 0.06573262,
        0.04911016, 0.03055974, 0.03075683, 0.03482464, 0.05674165,
        0.03055974, 0.03107213, 0.03490199, 0.05438699, 0.06155541,
        0.02927175, 0.02706807, 0.15097625, 0.06155541, 0.02923251,
        0.02701418, 0.20519673, 0.06037917, 0.02830685, 0.03017439,
        0.44331097, 0.06037917, 0.02827936, 0.03014001, 0.46921461]),
 'rank_test_score': array([25, 31, 36, 33, 25, 32, 35, 34, 19, 22, 30, 23, 19, 21, 29, 24, 17,
         8, 11, 27, 17,  7, 12, 28, 15,  3,  9, 37, 15,  4, 10, 38, 13,  1,
         5, 40, 13,  2,  6, 39], dtype=int32)}

In [29]:
table=pd.DataFrame.from_dict(result)
table=table.sort_values(by='rank_test_score')
svr_gridsearch_results = table[[
    'param_C',
    'param_gamma',
    'param_kernel',
    'mean_test_score',
    'rank_test_score'
]]
svr_gridsearch_results.columns = ['C', 'gamma', 'kernel', 'score', 'rank']
svr_gridsearch_results

       C  gamma   kernel     score  rank
33  3000  scale     poly  0.806743     1
37  3000   auto     poly  0.806718     2
25  2000  scale     poly  0.805582     3
29  2000   auto     poly  0.805576     4
34  3000  scale      rbf  0.796943     5
38  3000   auto      rbf  0.796941     6
21  1000   auto     poly  0.793555     7
17  1000  scale     poly  0.793265     8
26  2000  scale      rbf  0.783428     9
30  2000   auto      rbf  0.783396    10
18  1000  scale      rbf  0.706641    11
22  1000   auto      rbf  0.706625    12
32  3000  scale   linear  0.624750    13
36  3000   auto   linear  0.624750    13
24  2000  scale   linear  0.620053    15
28  2000   auto   linear  0.620053    15
16  1000  scale   linear  0.594383    17
20  1000   auto   linear  0.594383    17
12   100   auto   linear  0.583498    19
8    100  scale   linear  0.583498    19
13   100   auto     poly  0.510181    21
9    100  scale     poly  0.510155    22
11   100  scale  sigmoid  0.470546    23
15   100   auto  sigmoid  0.470105    24
4     10   auto   linear  0.367569    25
0     10  scale   linear  0.367569    25
19  1000  scale  sigmoid  0.329645    27
23  1000   auto  sigmoid  0.305471    28
14   100   auto      rbf  0.243024    29
10   100  scale      rbf  0.242982    30
1     10  scale     poly  0.001188    31
5     10   auto     poly  0.001107    32
3     10  scale  sigmoid -0.001635    33
7     10   auto  sigmoid -0.001657    34
6     10   auto      rbf -0.056625    35
2     10  scale      rbf -0.056634    36
27  2000  scale  sigmoid -0.397238    37
31  2000   auto  sigmoid -0.445127    38
39  3000   auto  sigmoid -1.588188    39
35  3000  scale  sigmoid -1.799025    40

In [33]:
svr_gridsearch_results.head(5)

       C  gamma kernel     score  rank
33  3000  scale   poly  0.806743     1
37  3000   auto   poly  0.806718     2
25  2000  scale   poly  0.805582     3
29  2000   auto   poly  0.805576     4
34  3000  scale    rbf  0.796943     5